language: c
env:
  global:
    secure: m8QW0/VPTTsuxETgLu97WIYzAww0FhQhwsMz5GOiVPBFntO0zCfvlHipMMWBIq1wSwlUGjxYq8rTFf47CMnP0h/C194OHKFJoQkBD9tKRpuH5nxsNL/JH1dLgP9G9xXSLJQkgfkVAZH8BbfUW3+y8oL1eqFKrrcOcloGi+Rc+nK62Hf7JSb6gfyVUgzeXyluCZPhYUnSrqsCExQYF7ZDQmrSQ3EMfNPxMH7JCFEd5jm9jQuEGUPVC8QT6Jrrg8FMhBl3015v37B3llrzAggwp5RydzSjdyb2cy0NuwEPeQB07G/WmrLfR4MrGzn3pfRNW2+YXjER9HdJ1t9Rvi7CFbhNorjJZXlVMwwuovVD5iYYDbntGGTy13yRTl0nzFv2G6s37RnbdWI19QdCs3U5emx/ZjDHwKc7QKl7YH32myVVil1E37Q+UCmOr7f+e9abUse9v3DUkcBm99V/yUlLq4TM2qKOt6Da1dPcoepF8Sju2cyOyNyHzNVAvkEMuw3MQM2qzedmeuij6B9YjTzjsLbrRZRuAZrPOOGCtCgSaU0AkP2AzLls3ERtm/atqCqlwvk/pQR8Zr+j9ScHl8grA10IbW2v4gpVKz/uJ99DAAvS2GFyvdTFWY2TpxOZ+ir01AbdRXZzkzWV2I6BBezMEEjed5rNYDnYuBKhDDpT+js=
branches:
  only:
  - master
  - release
before_install:
 "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
- sleep 3
- export DISPLAY=:1.0
- wget http://downloads.arduino.cc/arduino-1.8.10-linux64.tar.xz
- tar xf arduino-1.8.10-linux64.tar.xz
- sudo mv arduino-1.8.10 /usr/local/share/arduino
- sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
- source $TRAVIS_BUILD_DIR/install.sh
script:
  #- build_platform nrf52840
  #- build_platform esp32
  - build_platform uno
  #- build_platform leonardo
  #- build_platform zero
  - build_platform esp8266
  #- build_platform m4
script:
- arduino --verify --board arduino:avr:uno $PWD/TravisCIblink.ino
before_deploy:
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: m8QW0/VPTTsuxETgLu97WIYzAww0FhQhwsMz5GOiVPBFntO0zCfvlHipMMWBIq1wSwlUGjxYq8rTFf47CMnP0h/C194OHKFJoQkBD9tKRpuH5nxsNL/JH1dLgP9G9xXSLJQkgfkVAZH8BbfUW3+y8oL1eqFKrrcOcloGi+Rc+nK62Hf7JSb6gfyVUgzeXyluCZPhYUnSrqsCExQYF7ZDQmrSQ3EMfNPxMH7JCFEd5jm9jQuEGUPVC8QT6Jrrg8FMhBl3015v37B3llrzAggwp5RydzSjdyb2cy0NuwEPeQB07G/WmrLfR4MrGzn3pfRNW2+YXjER9HdJ1t9Rvi7CFbhNorjJZXlVMwwuovVD5iYYDbntGGTy13yRTl0nzFv2G6s37RnbdWI19QdCs3U5emx/ZjDHwKc7QKl7YH32myVVil1E37Q+UCmOr7f+e9abUse9v3DUkcBm99V/yUlLq4TM2qKOt6Da1dPcoepF8Sju2cyOyNyHzNVAvkEMuw3MQM2qzedmeuij6B9YjTzjsLbrRZRuAZrPOOGCtCgSaU0AkP2AzLls3ERtm/atqCqlwvk/pQR8Zr+j9ScHl8grA10IbW2v4gpVKz/uJ99DAAvS2GFyvdTFWY2TpxOZ+ir01AbdRXZzkzWV2I6BBezMEEjed5rNYDnYuBKhDDpT+js=
  file:
    - $ARDUINO_HEX_DIR/uno/TravisCIblink/TravisCIblink.ino.hex
    #- $ARDUINO_HEX_DIR/uno/TravisCIblink/TravisCIblink.ino.with_bootloader.hex
  skip_cleanup: true
  on:
    tags: true
  skip_cleanup: true
  #on:
    #tags: true
# Notifications after build
notifications: 
  #email:
  #recipients:
    #- 
  #on_success: always
  #on_failure: always
